### ISSUE TITLE
Remove me from the project

### ISSUE THREAD

**Issue by gino004** [BolotovKonstantine/wdd330-team#25]
Hi, I wanted to leave the project we are working on on GitHub but I can't do it. I think you could do it because you are the owner. If you can do it, please remove me from the project. Thanks.

**Comment by 0laf3** [comment]
Hi, thanks for reaching out. The owner of the project is BolotovKonstantine, so he should be able to assist you with this. I think you should contact him directly to have you removed from the project. Let me know if you need further help!

**Comment by gino004** [comment]
Hello, but there is no way to contact him, they kicked me out of the Microsoft Teams group, can someone tell him or give me a way to contact him?
